#!/usr/bin/env bash

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install ansible
brew install ansible

# Pull ansible
ansible-pull -U https://github.com/TortleWortle/ansible-dev.git macos.yml