- hosts: localhost
  pre_tasks:
  - name: Update brew
    shell: brew update
  tasks:
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/fnm.yml
  - import_tasks: tasks/nvim.yml
  - import_tasks: tasks/stow.yml
  - import_tasks: tasks/tmuxinator.yml
  - import_tasks: tasks/zsh.yml