- name: install zsh
  shell: brew install zsh
- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
  - install
  - zsh
- name: install atuin
  shell: brew install atuin
  tags:
  - install
- name: install zoxide
  shell: brew install zoxide
  tags:
  - install
- name: install asdf
  shell: brew install asdf
  tags:
  - install
- name: install tmux
  shell: brew install tmux
  tags:
  - install
- name: install tmux-sessionizer
  shell: brew install tmux-sessionizer
  tags:
  - install
